# Generated by Django 4.0.2 on 2022-03-19 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('countryOfOrigin', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('pattern', models.CharField(max_length=255)),
                ('plusSize', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DressItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.FloatField(default=0)),
                ('description', models.TextField(max_length=8191)),
                ('header', models.TextField(max_length=1023)),
                ('discount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FemalePantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.FloatField(default=0)),
                ('description', models.TextField(max_length=8191)),
                ('header', models.TextField(max_length=1023)),
                ('discount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FemaleShirtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.FloatField(default=0)),
                ('description', models.TextField(max_length=8191)),
                ('header', models.TextField(max_length=1023)),
                ('discount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KidClothesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.FloatField(default=0)),
                ('description', models.TextField(max_length=8191)),
                ('header', models.TextField(max_length=1023)),
                ('discount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MalePantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.FloatField(default=0)),
                ('description', models.TextField(max_length=8191)),
                ('header', models.TextField(max_length=1023)),
                ('discount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MaleShirtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.FloatField(default=0)),
                ('description', models.TextField(max_length=8191)),
                ('header', models.TextField(max_length=1023)),
                ('discount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FemaleClothes',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.clothes')),
                ('petite', models.BooleanField(default=False)),
                ('season', models.CharField(max_length=255)),
                ('occasion', models.CharField(max_length=255)),
            ],
            bases=('clothes.clothes',),
        ),
        migrations.CreateModel(
            name='KidClothes',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.clothes')),
                ('gender', models.CharField(max_length=255)),
                ('recommendedAge', models.CharField(max_length=255)),
            ],
            bases=('clothes.clothes',),
        ),
        migrations.CreateModel(
            name='MaleClothes',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.clothes')),
                ('tallFit', models.BooleanField(default=False)),
            ],
            bases=('clothes.clothes',),
        ),
        migrations.CreateModel(
            name='MaleShirtItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/male_shirt_item_images/')),
                ('maleShirtItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.maleshirtitem')),
            ],
        ),
        migrations.CreateModel(
            name='MalePantItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/male_pant_item_images/')),
                ('malePantItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.malepantitem')),
            ],
        ),
        migrations.CreateModel(
            name='KidClothesItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/kid_clothes_item_images/')),
                ('kidClothesItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.kidclothesitem')),
            ],
        ),
        migrations.CreateModel(
            name='FemaleShirtItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/female_shirt_item_images/')),
                ('femaleShirtItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.femaleshirtitem')),
            ],
        ),
        migrations.CreateModel(
            name='FemalePantItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/female_pant_item_images/')),
                ('femalePantItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.femalepantitem')),
            ],
        ),
        migrations.CreateModel(
            name='DressItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/dress_item_images/')),
                ('dressItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.dressitem')),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('maleclothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.maleclothes')),
                ('length', models.FloatField()),
                ('style', models.CharField(max_length=255)),
            ],
            bases=('clothes.maleclothes',),
        ),
        migrations.CreateModel(
            name='FemalePant',
            fields=[
                ('maleclothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.maleclothes')),
                ('bottomsLength', models.FloatField()),
                ('waistHeight', models.FloatField()),
            ],
            bases=('clothes.maleclothes',),
        ),
        migrations.CreateModel(
            name='FemaleShirt',
            fields=[
                ('maleclothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.maleclothes')),
                ('neckline', models.CharField(max_length=255)),
                ('croppedTop', models.BooleanField(default=False)),
                ('topLength', models.FloatField()),
                ('sleeveLength', models.FloatField()),
            ],
            bases=('clothes.maleclothes',),
        ),
        migrations.CreateModel(
            name='MalePant',
            fields=[
                ('maleclothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.maleclothes')),
                ('length', models.FloatField()),
            ],
            bases=('clothes.maleclothes',),
        ),
        migrations.CreateModel(
            name='MaleShirt',
            fields=[
                ('maleclothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.maleclothes')),
                ('sleeveLength', models.FloatField()),
            ],
            bases=('clothes.maleclothes',),
        ),
        migrations.AddField(
            model_name='kidclothesitem',
            name='kidClothes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clothes.kidclothes'),
        ),
        migrations.AddField(
            model_name='maleshirtitem',
            name='maleShirt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clothes.maleshirt'),
        ),
        migrations.AddField(
            model_name='malepantitem',
            name='malePant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.malepant'),
        ),
        migrations.AddField(
            model_name='femaleshirtitem',
            name='femaleShirt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clothes.femaleshirt'),
        ),
        migrations.AddField(
            model_name='femalepantitem',
            name='femalePant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clothes.femalepant'),
        ),
        migrations.AddField(
            model_name='dressitem',
            name='dress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clothes.dress'),
        ),
    ]
