# Generated by Django 4.0.2 on 2022-03-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookitem',
            old_name='prices',
            new_name='price',
        ),
    ]
