# Generated by Django 4.0.2 on 2022-03-15 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_rename_prices_bookitem_price'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('shippingFee', models.FloatField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('bookItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookItems', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='CartBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('bookItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookitem')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookItems', to='order.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.payment')),
                ('number', models.CharField(max_length=15)),
                ('bankId', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='order.order')),
            ],
            bases=('order.payment',),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.payment')),
                ('number', models.CharField(max_length=15)),
                ('expDate', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='order.order')),
            ],
            bases=('order.payment',),
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.payment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='order.order')),
            ],
            bases=('order.payment',),
        ),
    ]
